"""empty message

Revision ID: 3470ef61cdc3
Revises: 
Create Date: 2022-07-20 03:59:57.993218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3470ef61cdc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'students', ['email'])
    op.create_unique_constraint(None, 'students', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    # ### end Alembic commands ###
